# Generated by Django 5.0.1 on 2026-02-19 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=200)),
                ('carrier_name', models.CharField(max_length=200)),
                ('main_office_address', models.CharField(max_length=500)),
                ('home_terminal_address', models.CharField(max_length=500)),
                ('truck_number', models.CharField(max_length=100)),
                ('shipping_docs', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'eld_carrier_info',
            },
        ),
        migrations.CreateModel(
            name='HosConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('min_off_duty_before_shift_hours', models.FloatField(default=10)),
                ('max_driving_hours', models.FloatField(default=11)),
                ('max_duty_window_hours', models.FloatField(default=14)),
                ('allow_driving_after_duty_window', models.BooleanField(default=False)),
                ('required_break_after_driving_hours', models.FloatField(default=8)),
                ('break_duration_minutes', models.IntegerField(default=30)),
                ('break_must_be_continuous', models.BooleanField(default=True)),
                ('default_cycle', models.CharField(choices=[('60_in_7', '60 hours in 7 days'), ('70_in_8', '70 hours in 8 days')], default='70_in_8', max_length=20)),
                ('restart_enabled', models.BooleanField(default=True)),
                ('restart_duration_hours', models.IntegerField(default=34)),
                ('restart_must_be_continuous', models.BooleanField(default=True)),
                ('extended_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'eld_hos_configuration',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'eld_location',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=500)),
                ('pickup', models.CharField(max_length=500)),
                ('dropoff', models.CharField(max_length=500)),
                ('cycle_hours_used', models.FloatField(default=0)),
                ('start_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrier_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eld_api.carrierinfo')),
            ],
            options={
                'db_table': 'eld_trip',
            },
        ),
        migrations.CreateModel(
            name='RouteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_miles', models.FloatField()),
                ('duration_hours', models.FloatField()),
                ('polyline', models.JSONField()),
                ('instructions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dropoff_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_as_dropoff', to='eld_api.location')),
                ('origin_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_as_origin', to='eld_api.location')),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_as_pickup', to='eld_api.location')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='eld_api.trip')),
            ],
            options={
                'db_table': 'eld_route_result',
            },
        ),
        migrations.CreateModel(
            name='DutyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty_not_driving', 'On Duty (Not Driving)')], max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(max_length=500)),
                ('remarks', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_events', to='eld_api.trip')),
            ],
            options={
                'db_table': 'eld_duty_event',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_miles', models.FloatField(default=0)),
                ('off_duty_hours', models.FloatField(default=0)),
                ('sleeper_berth_hours', models.FloatField(default=0)),
                ('driving_hours', models.FloatField(default=0)),
                ('on_duty_not_driving_hours', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='eld_api.trip')),
            ],
            options={
                'db_table': 'eld_daily_log',
                'ordering': ['date'],
                'unique_together': {('trip', 'date')},
            },
        ),
    ]
