# Generated by Django 5.0.1 on 2026-02-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='hos_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='trip',
            name='intel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
