# Generated by Django 5.0.1 on 2026-02-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_api', '0002_trip_hos_config_trip_intel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyevent',
            name='miles',
            field=models.FloatField(default=0, help_text='Miles covered during this event'),
        ),
    ]
