# Generated by Django 5.0.1 on 2026-02-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_api', '0003_dutyevent_miles'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyevent',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Local timezone for this event location', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='timezone',
            field=models.CharField(default='UTC', help_text="IANA timezone identifier (e.g., 'America/Los_Angeles')", max_length=50),
        ),
        migrations.AddField(
            model_name='trip',
            name='dropoff_timezone',
            field=models.CharField(default='UTC', help_text='Timezone at dropoff location', max_length=50),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin_timezone',
            field=models.CharField(default='UTC', help_text='Timezone at origin location', max_length=50),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_timezone',
            field=models.CharField(default='UTC', help_text='Timezone at pickup location', max_length=50),
        ),
    ]
