# Generated by Django 5.0.1 on 2026-02-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_api', '0004_dutyevent_timezone_location_timezone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dutyevent',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='location',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='dropoff_timezone',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='origin_timezone',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='pickup_timezone',
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dutyevent',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dutyevent',
            name='status',
            field=models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty_not_driving', 'On Duty (Not Driving)')], db_index=True, max_length=50),
        ),
    ]
