# Generated by Django 5.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_api', '0005_remove_dutyevent_timezone_remove_location_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrierinfo',
            name='co_driver_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
